var homePage = {
	
	postTaskButton: '#menu-cta > a.post-task-link.plain-text',
	
	root_URL: '/',
	dashboard_URL: '/account/dashboard/',
	payments_URL: '/account/payments/',
	profile_URL: '/account/profile/',
	preLogin_postTask_URL: '/post-task/',
	postLogin_postTask_URL: '/account/dashboard/post-task/',
	browseTasks_URL: '/tasks/',
	postSignup_registration_URL: '/sign-up/user-registration/',
	profile_URL: '/account/profile/',
	postTask_signUpContext_URL: '/post-task/sign-up/?context=post-task',
	postTask_dashboard_URL: '/account/dashboard/post-task/',
	writeReview_URL: '/tasks/<taskslug>/write-review/<taskslug>/', //todo
	title: 'Hire skilled people & earn extra money today on Airtasker.com',
	postTaskLink: '#header #menu-cta .post-task-link',
	postTaskForm: '#task-form',
	taskPostedSuccessNoLoader: '#task-form > div.loader-container > div',
	taskPostedSuccessNoLoaderClass: 'loaderific-not-loading',
	postTaskFormTitle: '#form-title',
	postTaskFormTitleValue: 'Get FREE Quotes',
	browseTasksLink: '#header #menu-cta .browse-tasks-link',
	loginForm: '#dialog-stack > div:nth-child(2) > dialogiv > div > div.login-form',

	openTasksLink: '#tasks-menu > div.tasks-menu.web > a.open-tasks',
	
	howItWorksLink: '#header #menu-cta .how-it-works-link',
	postTaskTitle: '.post-task-form #post-task-title',
	errorMessage: '.error-message',
	postTaskDescriptionInput: '#post-task-description',
	taskDetailsButton: '#ui-test-task-details-button',
	templateContinueButton: '#ui-test-template-continue-button',
	toggleLogin: '#toggle-login',
	loginLink: 'Login',
	emailInput: '#email-input',
	passwordInput: '#password-input',
	loginButton: '.dialog .login-form #login-button',
	signupButton: '.dialog .login-form #sign-up-button',
	
	facebookLoginCTA: 'div.login-form > div.dialog-panel-body > div > div:nth-child(2) > div:nth-child(1) > button',
	facebookLoginEmail: '#email',
	facebookLoginPassword: '#pass',
	facebookLoginButton: '#loginbutton',
	
	taskDetailsButton: '.dialog .post-task-form #ui-test-task-details-button',
	taskLocationButton: '#ui-test-location-button',
	recurringDateButton: '#ui-test-recurring-date-button',
	dialog: '#dialog-stack',
	formLocationInput: '.post-task-form #location-input',
	physicalOrOnline: '#physical-or-online',
	physicalTask: '#physical-task',
	onlineTask: '#online-task',
	onceOffTask: '#once-off-input',
	recurringTask: '#recurring-input',
	dueToday: '#completed-Today0',
	postTaskPayTotal: '#post-task-pay-total',
	postTaskPayHourly: '#post-task-pay-hourly',
	dueDateSelection: '#recurring-date-step > div.margin-20-top > div.air-date-picker > div > div.cell.input-cell > div',
	recurringInterval: '#recurring-interval-input',
	recurringInterval_2_weeks: '.air-select option:nth-child(2)',
	completedByCertainDay: '#date-picker-component > form > div.radio-set.margin-10-bottom > span:nth-child(2) > label',
	datePicker: 'body > div.react-datepicker__tether-element.react-datepicker__tether-element-attached-top.react-datepicker__tether-element-attached-left.react-datepicker__tether-target-attached-bottom.react-datepicker__tether-target-attached-left.react-datepicker__tether-enabled > div > div.react-datepicker__month',
	neverEndingTask: '#never-ends-input',
	recurringEndingDate: '#recurring-ends-input',
	recurringEndDateSelection: '#recurring-date-step > div:nth-child(3) > div:nth-child(2) > div.air-date-picker > div > div.cell.input-cell > div',
	recurringEndingDatePicker: 'body > div.react-datepicker__tether-element.react-datepicker__tether-element-attached-top.react-datepicker__tether-element-attached-left.react-datepicker__tether-target-attached-bottom.react-datepicker__tether-target-attached-left.react-datepicker__tether-enabled > div > div.react-datepicker__month',
	recurringDateStep: '#recurring-date-step',
	paymentAmount: '#post-task-payment-amount',
	pricingButton: '#ui-test-pricing-button',
	allDoneButton: '#ui-test-all-done-button',
	
	loginLink_landing_page: '#menu-user > a.link.login-link',
	signupLink_landing_page: '#menu-user > a.link.sign-up-link',
	
	/* User Menu Items */
	menu: '//*[@id="menu-user"]/a[1]/div[2]',
	dashboardMenu: '#menu-popup > div:nth-child(1) > div > a.button.selected',
	settingsMenu: '#menu-popup > div:nth-child(2) > div.menu-folder-control.showing > a',
	PaymentsHistoryMenu: '#menu-popup > div:nth-child(1) > div > a:nth-child(7)',
	profileMenu: '#menu-popup > div.menu-folder.expanded > div.menu-folder-items.showing > a:nth-child(1)',
	logoutButton: '//*[@id="menu-popup"]/div[5]/div/a',
	
	closeDialog: 'div.close-cross',
	
	/* site alert */
	siteAlertButton: '#header > div.site-alert > div > div.message-content.message-tail > button',
	termsConditionsText: 'I Agree to the Terms & Conditions',
	/* Onboarding Section */
	userRegistrationForm: 'div.user-registration-form',
	userRegistrationHeader: 'div.dialog-panel-header > div',
	signupSuccessMessage: 'Welcome!',
	newUserOnbardingFirstName: '#first-name',
	newUserOnbardingLastName: '#last-name',
	newUserOnbardingSuburb: '#location-input',
	locationSuggestion: '#dialog-stack > div:nth-child(2) > div > div > div > div.dialog-panel-body > div > div:nth-child(3) > div > div',
	chooseWorkerProfile: '#is-runner',
	choosePosterProfile: '#is-sender',
	createProfileButton: '#ui-test-create-profile-button',
	onboardingStepDialog: '#dialog-stack > div > div > div > div.anchovy-form > div',
	onboardingHeader: 'div.dialog-panel-header.border-none.with-subheading > div:nth-child(1)',
	uploadAvatarHeaderMessage: 'Upload a profile picture',
	
	postTaskLocationInput: '#location-input',
	
	uploadAvatarInputButton: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-body > div > div > div.attachment-input-holder > div.attachment-input > input[type="file"]',
	uploadAvatarVisibleButton: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-body > div > div > div.attachment-input-holder > div.attachment-input',
	uploadAvatarFinalButton: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-body > div > div > div.attachment-input-holder > div.attachment-upload.button-cta.button-med',
	avatarUploadedSuccessNoLoader: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-body > div > div > div.loaderific-not-loading',
	
	mainLoader: '#page-and-screen-content > div.content > div > div.task-list > div.loaderific-not-loading',
	
	addSkillsHeaderMessage: 'Let us know what your skills are',
	
	addMobileNumberMessage: 'Mobile Number',
	mobileNumberInput: '#newMobile',
	sendVerificationCodeButton: 'div.anchovy-verify-mobile.anchovy-form-item > div.margin-10-top > button',
	
	verificationCodeSentDialog: 'div.generic-alert.anchovy-form',
	verificationCodeHeader: 'div.generic-alert.anchovy-form > div.dialog-panel-header',
	verificationCodeSentSuccessMsgTitle: 'Verification Code Sent',
	verificationCodeBody: 'div.generic-alert.anchovy-form > div.dialog-panel-body > div > div',
	verificationCodeBodyMessage: 'You should receive a 6-digit mobile verification code in a few minutes.',
	verificationAlertOKButton: 'div.generic-alert.anchovy-form > div.dialog-panel-footer > button',
	
	verificationCodeInput: '#verificationCode',
	verificationCodeDisplay: 'div.anchovy-verify-mobile.anchovy-form-item > div',
	
	verifyMobileButton: 'div.anchovy-verify-mobile.anchovy-form-item > div:nth-child(5) > button',
	verificationCodeChangeButton: 'div.anchovy-verify-mobile.anchovy-form-item > button.button-min.button-sml.change-mobile',
	verificationCodeRemoveButton: 'div.anchovy-verify-mobile.anchovy-form-item > button.button-min.button-sml.remove-mobile',
	
	moreAboutYouDialogHeaderMessage: 'Tell us more about you',
	moreAboutYouDescriptionInput: '#description-input',
	
	paymentDetailsDialogHeaderMessage: 'Enter your payment details',
	accountHolderNameInput: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-body > div > div > div.margin-10-0 > div > div:nth-child(1) > input',
	bsbInput: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-body > div > div > div.margin-10-0 > div > div:nth-child(2) > input',
	accountNumberInput: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-body > div > div > div.margin-10-0 > div > div:nth-child(3) > input',
	addBankAccountButton: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-body > div > div > div.margin-10-0 > button',
	addBankAccountSuccessNoLoader: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-body > div > div > div.loaderific-not-loading',
	
	checkOutAvailableWorkHeaderMessage: 'Check out available work',
	chooseTaskHeaderMessage: 'Choose the task that suits you best',
	completeTaskHeaderMessage: 'Complete tasks & start earning',
	
	onboardingNextButton: '#dialog-stack > div > div > div > div.anchovy-form > div > div.dialog-panel-footer.anchovy-buttons > button.button-cta.button-med.next',
	onboardingFinalButton: '#info-screen-three > div.dialog-panel-footer.anchovy-buttons > button.button-cta.button-med.next',
	
	paymentMethodBillingAddress: '#page-and-screen-content > div.content > div > div.account.vertical-scroll > div.account-payments > div:nth-child(4) > div.splitter-section-content > div > div.anchovy-form > div:nth-child(1) > div > div:nth-child(1) > input',
	paymentMethodPostCode: '#page-and-screen-content > div.content > div > div.account.vertical-scroll > div.account-payments > div:nth-child(4) > div.splitter-section-content > div > div.anchovy-form > div:nth-child(1) > div > div:nth-child(2) > input',
	paymentMethodCity: '#page-and-screen-content > div.content > div > div.account.vertical-scroll > div.account-payments > div:nth-child(4) > div.splitter-section-content > div > div.anchovy-form > div:nth-child(1) > div > div:nth-child(3) > input',
	paymentMethodState: '#page-and-screen-content > div.content > div > div.account.vertical-scroll > div.account-payments > div:nth-child(4) > div.splitter-section-content > div > div.anchovy-form > div:nth-child(1) > div > div:nth-child(4) > input',
	paymentMethodCountry: '#page-and-screen-content > div.content > div > div.account.vertical-scroll > div.account-payments > div:nth-child(4) > div.splitter-section-content > div > div.anchovy-form > div:nth-child(1) > div > div:nth-child(5) > input',
	paymentMethodAddBillingAddressButton: '#page-and-screen-content > div.content > div > div.account.vertical-scroll > div.account-payments > div:nth-child(4) > div.splitter-section-content > div > div.anchovy-form > div:nth-child(1) > button',
	paymentMethodBillingAddressRemoveButton: '#page-and-screen-content > div.content > div > div.account.vertical-scroll > div.account-payments > div:nth-child(4) > div.splitter-section-content > div > div.anchovy-form > div:nth-child(1) > button',

	profileBirthdayDate: '#date-of-birth-input > input.date',
	profileBirthdayMonth: '#date-of-birth-input > input.month',
	profileBirthdayYear: '#date-of-birth-input > input.year',
	profileSaveButton: '#ui-test-begin-save',
	
	noLoaderClass: 'loaderific-not-loading',
	loaderClass: 'loaderific',
	
	taskSettingsButton: '#show-settings-button',
	taskTypeWithLocation: '#page-and-screen-content > div.content > div > div.task-list > div.task-search > div.padder-0-10 > div:nth-child(2) > div.button-bar > a:nth-child(2)',
	baseLocation: '#location-input',
	updateButton: '#update-button',
	taskIDforRegression: '#automated-visual-regression-354701',
	
	taskListItem: '.task-list .task-list-item',
	dataTaskId: 'data-task-id',
	taskDetails: '.task-details',
	taskActivityComments: '.task-details .task-activity-comments',
	commentTextArea: 'div.add-comm-form.anchovy-form > div.text-area > div > textarea',
	commentSendButton: 'div.add-comm-form.anchovy-form > div.buttons > button',
	commentSentLoader: 'div.add-comm-form.anchovy-form > div.loaderific-not-loading',
	
	
	redeemCardButton: 'div.redeem-screen > div.intro-container > div > div.text-container > button',
	redeemCardURL: '/redeem/enter-redeem-code/',
	redeemCardDialog: 'div.redeem-dialog.anchovy-form',
	redeemCardHeader: 'div.redeem-dialog.anchovy-form > div.dialog-panel-header',
	redeemCardHeaderMessage: 'Airtasker Card',
	redeemCode: '6666666666666666666',
	redeemCardNumber: '#ui-test-enter-code',
	redeemCardSubmitButton: 'div.redeem-dialog.anchovy-form > div.dialog-panel-footer > button',
	redeemSuccessDialog: 'div.redeem-dialog.anchovy-form',
	redeemSuccessHeader: 'div.redeem-dialog.anchovy-form > div.dialog-panel-header',
	redeemSuccessHeaderMessage: 'Task Credit redeemed',
	redeemSuccessGoToDashboard: 'div.redeem-dialog.anchovy-form > div.dialog-panel-footer > button',
	
	/* IKEA */

	button: 'button',
	getStarted: 'Get started',
	articleSearchField: '#product-search-input',
	ikeaArticle: 'box',
	articleSuggestionQuantity: '#ikea-product-select > div.search-area > div > div.ikea-product-search > div.search-results > div > div:nth-child(1) > div > div:nth-child(3) > div.number-incrementor > div > input[type="number"]',
	articleSuggestionQuantityIncrement: '#ikea-product-select > div.search-area > div > div.ikea-product-search > div.search-results > div > div:nth-child(1) > div > div:nth-child(3) > div.number-incrementor > div > button:nth-child(3)',
	articleSuggestionAdd: '#ikea-product-select > div.search-area > div > div.ikea-product-search > div.search-results > div > div:nth-child(1) > div > div:nth-child(5) > button',
	articleListFinalQuantity: '#ikea-product-select > div.margin-20-0 > div > div.item-list-container > div > div > div:nth-child(3) > div.number-incrementor > div > input[type="number"]',
	totalEstimatedBudget: '#ikea-post-task-footer > div > div > table > tbody > tr.text-h5 > td:nth-child(1)',
	ikeaContinue: '#ikea-post-task-footer > div > button',
	ikeaSignupURL: '/sign-up/',
	ikeaPostTaskTitle: '#ikea-post-task-body > div:nth-child(1) > div.ikea-post-task-details > div > div:nth-child(1) > input',
	ikeaPostTaskTitleValue: 'IKEA - Furniture Assembly',
	ikeaContinueButton: '#ikea-post-task-footer > button',
	ikeaDueToday: '#date-picker-component > form > div.radio-set.margin-10-bottom > span:nth-child(1) > label',
	ikeaDueDueCertainDay: '#date-picker-component > form > div.radio-set.margin-10-bottom > span:nth-child(2) > label',
	ikeaDueInAWeek: '#date-picker-component > form > div.radio-set.margin-10-bottom > span:nth-child(3) > label',
	ikeaEstimatedBudget: '#task-budget-input',
	getQuotes: 'Get Quotes Now',
	ikeaTaskPostedMessage: '#ikea-post-task-body > div.ikea-post-task-confirmation > div.content.content-xs > h3',
	ikeaTaskPostedMessageValue: 'Congratulations!'

	
};

module.exports = homePage;
